### ISSUE TITLE
能否支持PG的wal方式复制，不用逻辑复制

### ISSUE THREAD

**Issue by wwwwwwchun** [hellobike/amazonriver#18]
能否支持的PG的wal物理文件方式的复制，不用逻辑方式，因为PG在用逻辑方式复制后，会出现主从延迟高的问题。

**Comment by cqyzh** [comment]
请问一下，我配置好了之后，始终无法在kafka中自动创建指定的topic，感觉无法与kafka进行通信，你知道怎么解决吗？

**Comment by cqyzh** [comment]
请问一下，我配置好了之后，始终无法在kafka中自动创建指定的topic，感觉无法与kafka进行通信，大家知道怎么解决吗？

**Comment by xiaoma20082008** [comment]
@wwwwwwchun 不支持物理复制，ps：PG的物理复制是基于文件的，无法回放单行记录
@cqyzh kafka topic需要您提前创建好，然后再使用！
