### ISSUE TITLE
发送到kafka失败的消息内容是否记录，在哪里？

### ISSUE THREAD

**Issue by xiaomeng79** [hellobike/amazonriver#27]
INFO[0366] producer/leader/student_name_logs/0 state change to [normal] 
ERRO[0366] write kafka msg err: kafka: Failed to deliver 2102 messages.

**Comment by xiaoma20082008** [comment]
失败时不会ack数据库最后一次的lsn，下个发送周期会重发，请注意去重！

**Comment by xiaomeng79** [comment]
您好，amazonriver_error{instance="192.168.10.128:8080",job="syncdb",slot_name="slot_for_kafka"}  10   这个统计错误的，我看有错误，能知道这些错误是那些数据吗？想核查一下

**Comment by xiaoma20082008** [comment]
发送失败的消息，都看不到，没有记录。因为失败了不会ack lsn，所以一般会重发

**Comment by xiaomeng79** [comment]
好的，谢谢
